include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    duplicate_ignore: ignore
    no_wildcard_variable_uses: ignore
      
linter:
  rules:
    library_prefixes: false
    prefer_function_declarations_over_variables: false
